# Generated by Django 5.2.4 on 2025-08-03 19:21

import Services.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0007_bulkemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Service/Skill title', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of your service/skill')),
                ('category', models.CharField(choices=[('technology', 'Technology & Digital'), ('creative', 'Creative & Design'), ('business', 'Business Services'), ('home', 'Home & Lifestyle'), ('health', 'Health & Beauty'), ('professional', 'Professional Services')], help_text='Main service category', max_length=20)),
                ('service_type', models.CharField(choices=[('skill', 'Professional Skill'), ('service', 'Service Offering'), ('consultation', 'Consultation'), ('maintenance', 'Maintenance & Support'), ('training', 'Training/Teaching')], default='skill', max_length=20)),
                ('skills_offered', models.TextField(blank=True, help_text='Main skills/services you offer (comma-separated)')),
                ('tools_used', models.TextField(blank=True, help_text='Tools, software, or equipment you use')),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate'), ('project', 'Per Project'), ('package', 'Package Deal'), ('negotiable', 'Negotiable')], default='negotiable', max_length=20)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price (per hour/project/fixed)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price for negotiable services', max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price for negotiable services', max_digits=10, null=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (0-2 years)'), ('intermediate', 'Intermediate (3-5 years)'), ('experienced', 'Experienced (6-10 years)'), ('expert', 'Expert (10+ years)')], default='intermediate', max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True)),
                ('availability', models.CharField(choices=[('full_time', 'Full Time Available'), ('part_time', 'Part Time Available'), ('weekends', 'Weekends Only'), ('flexible', 'Flexible Schedule'), ('by_appointment', 'By Appointment')], default='flexible', max_length=20)),
                ('delivery_method', models.CharField(choices=[('remote', 'Remote/Online'), ('onsite', 'On-site'), ('both', 'Both Remote & On-site'), ('client_location', 'At Client Location'), ('my_location', 'At My Location')], default='both', max_length=20)),
                ('delivery_time', models.CharField(blank=True, help_text="e.g., '24 hours', '3-5 days'", max_length=100)),
                ('languages', models.CharField(default='English', help_text='Languages you work in', max_length=255)),
                ('requirements', models.TextField(blank=True, help_text='What you need from clients')),
                ('what_you_get', models.TextField(blank=True, help_text='What clients will receive')),
                ('extra_services', models.TextField(blank=True, help_text='Additional services you can provide')),
                ('portfolio_url', models.URLField(blank=True, help_text='Link to your portfolio/website')),
                ('certifications', models.TextField(blank=True, help_text='Relevant certifications or qualifications')),
                ('contact_instructions', models.TextField(blank=True, help_text='How clients should contact you')),
                ('serves_nationwide', models.BooleanField(default=True, help_text='Do you serve clients nationwide?')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('inquiry_count', models.PositiveIntegerField(default=0)),
                ('hire_count', models.PositiveIntegerField(default=0)),
                ('boost_score', models.DecimalField(decimal_places=2, default=0, help_text='Combined score for sorting', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('deletion_warning_sent', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.location')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_listings', to='User.profile')),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Listing',
                'verbose_name_plural': 'Service Listings',
                'ordering': ['-is_featured', '-boost_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(help_text='Describe your project/requirement')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Your budget for this project', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('timeline', models.CharField(blank=True, help_text='When do you need this completed?', max_length=255)),
                ('requirements', models.TextField(blank=True, help_text='Specific requirements')),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('platform', 'Through Platform')], default='platform', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Provider Responded'), ('negotiating', 'Negotiating'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider_response', models.TextField(blank=True)),
                ('provider_quote', models.DecimalField(blank=True, decimal_places=2, help_text="Provider's quoted price", max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_inquiries', to='User.profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='Services.servicelisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Services.models.service_image_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Services.servicelisting')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=Services.models.service_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('certificate', 'Certificate'), ('portfolio', 'Portfolio Sample'), ('testimonial', 'Client Testimonial'), ('license', 'Professional License'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Services.servicelisting')),
            ],
            options={
                'ordering': ['document_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='service_conversations', to='User.profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='Services.servicelisting')),
            ],
        ),
        migrations.CreateModel(
            name='SavedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_services', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='Services.servicelisting')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('encrypted_content', models.BinaryField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('inquiry_type', models.CharField(choices=[('AVAILABILITY', 'Are you available for this project?'), ('MORE_INFO', 'I would like more information about your service'), ('PRICE_NEGOTIATION', 'Can we discuss the pricing?'), ('TIMELINE', 'What is your expected timeline for this project?'), ('PORTFOLIO', 'Can you share more examples of your work?'), ('PAYMENT_METHOD', 'What payment methods do you accept?'), ('REVISIONS', 'How many revisions are included?'), ('EXPERIENCE', 'What is your experience with similar projects?'), ('CUSTOM', 'Custom message')], max_length=20)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Services.serviceconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_service_messages', to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or Misleading Content'), ('fraud', 'Fraudulent Service'), ('inappropriate', 'Inappropriate Content'), ('scam', 'Suspected Scam'), ('fake', 'Fake Service'), ('other', 'Other Reason')], max_length=20)),
                ('details', models.TextField()),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_service_reports', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Services.servicelisting')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('communication_rating', models.IntegerField(blank=True, help_text='Rate communication', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality_rating', models.IntegerField(blank=True, help_text='Rate work quality', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness_rating', models.IntegerField(blank=True, help_text='Rate timeliness', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Services.servicelisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_review_replies_given', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Services.servicereview')),
            ],
            options={
                'verbose_name_plural': 'Service Review Replies',
            },
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['is_active'], name='Services_se_is_acti_1211f5_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['category', 'is_active'], name='Services_se_categor_62da2d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['provider', '-created_at'], name='Services_se_provide_c65d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['-boost_score', '-created_at'], name='Services_se_boost_s_0d9212_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['expiration_date', 'is_active'], name='Services_se_expirat_c277d3_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinquiry',
            index=models.Index(fields=['service', '-created_at'], name='Services_se_service_f055b0_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinquiry',
            index=models.Index(fields=['client', '-created_at'], name='Services_se_client__346a48_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinquiry',
            index=models.Index(fields=['status', '-created_at'], name='Services_se_status_45a275_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceinquiry',
            unique_together={('service', 'client')},
        ),
        migrations.AddIndex(
            model_name='serviceconversation',
            index=models.Index(fields=['service', '-updated_at'], name='Services_se_service_860171_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceconversation',
            index=models.Index(fields=['-updated_at'], name='Services_se_updated_d605e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedservice',
            unique_together={('user', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='servicereview',
            unique_together={('service', 'reviewer')},
        ),
    ]
