# Generated by Django 5.2.4 on 2025-12-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceconversation',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='serviceconversation',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicemessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='servicemessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='service',
        ),
        migrations.DeleteModel(
            name='SavedService',
        ),
        migrations.DeleteModel(
            name='ServiceConversation',
        ),
        migrations.DeleteModel(
            name='ServiceMessage',
        ),
        migrations.DeleteModel(
            name='ServiceReport',
        ),
    ]
