# Generated by Django 5.2.4 on 2026-01-04 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_remove_serviceconversation_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='delivery_days',
            field=models.PositiveIntegerField(default=7, help_text='Expected delivery time in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='revision_limit',
            field=models.PositiveIntegerField(default=2, help_text='Number of revisions included (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
