# Generated by Django 5.2.4 on 2026-03-18 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0004_add_conversation_to_inquiry'),
        ('Services', '0003_servicelisting_delivery_days_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceinquiry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_inquiry', to='Messages.conversation'),
        ),
    ]
