# Generated by Django 5.2.4 on 2026-05-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_add_conversation_to_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelisting',
            name='service_type',
            field=models.CharField(choices=[('skill', 'Professional Skill'), ('service', 'Service Offering'), ('consultation', 'Consultation'), ('maintenance', 'Maintenance & Support'), ('training', 'Training/Teaching')], max_length=20),
        ),
    ]
