# Generated by Django 5.2.4 on 2026-06-23 22:02

import Services.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_alter_servicelisting_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=Services.models.service_image_path),
        ),
    ]
