# Generated by Django 5.2.4 on 2025-10-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_virtualaccount_monnifytransaction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='virtualaccount',
            unique_together={('account_reference', 'bank_code')},
        ),
        migrations.AlterField(
            model_name='monnifytransaction',
            name='payment_reference',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='monnifytransaction',
            name='transaction_reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='notification_type',
            field=models.CharField(choices=[('SUCCESSFUL_TRANSACTION', 'Successful Transaction'), ('FAILED_TRANSACTION', 'Failed Transaction'), ('REVERSED_TRANSACTION', 'Reversed Transaction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='account_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='account_reference',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_accounts', to='Dashboard.useraccount'),
        ),
        migrations.RemoveField(
            model_name='virtualaccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='virtualaccount',
            name='expires_at',
        ),
    ]
