# Generated by Django 5.2.4 on 2025-11-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_virtualaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountstatus',
            old_name='yearly_price',
            new_name='two_month_price',
        ),
    ]
