# Generated by Django 5.2.4 on 2025-11-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_username_referral_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refund_of_transaction',
            field=models.ForeignKey(blank=True, help_text='Original transaction this refund is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='Dashboard.transaction'),
        ),
    ]
