# Generated by Django 5.2.4 on 2026-01-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_transaction_refund_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateprofile',
            name='minimum_withdrawal',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
    ]
