# Generated by Django 5.2.4 on 2026-05-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_alter_affiliateprofile_minimum_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('listing_fee', 'Listing Fee'), ('boost_fee', 'Boost Fee'), ('subscription', 'Subscription'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('transfer_in', 'Transfer Received'), ('transfer_out', 'Transfer Sent')], max_length=20),
        ),
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, help_text='Optional message to recipient', max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='completed', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='Dashboard.useraccount')),
                ('recipient_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_received', to='Dashboard.transaction')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='Dashboard.useraccount')),
                ('sender_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_sent', to='Dashboard.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', '-created_at'], name='Dashboard_w_sender__e683a4_idx'), models.Index(fields=['recipient', '-created_at'], name='Dashboard_w_recipie_3e97c0_idx')],
            },
        ),
    ]
