# Generated by Django 5.2.4 on 2026-06-23 22:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_alter_transaction_transaction_type_wallettransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Auto-generated unique reference e.g. WDR-A1B2C3D4E5F6', max_length=60, null=True, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Amount the user wants to withdraw (before fee)', max_digits=10)),
                ('fee_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Fee percentage locked at submission time (default 10%)', max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='Fee in naira, calculated and locked at submission', max_digits=10)),
                ('net_payout', models.DecimalField(decimal_places=2, help_text='Amount the user will actually receive (requested - fee)', max_digits=10)),
                ('withdrawable_balance_at_submission', models.DecimalField(decimal_places=2, help_text="User's withdrawable balance at the time of submission", max_digits=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(help_text="Must match user's verified identity on OpenSell", max_length=255)),
                ('proof_type', models.CharField(choices=[('monnify_reference', 'Monnify Transaction Reference'), ('bank_alert', 'Bank Debit Alert Upload'), ('both', 'Both Reference and Upload')], default='monnify_reference', max_length=30)),
                ('monnify_reference_manual', models.CharField(blank=True, help_text='If user types in their Monnify reference manually', max_length=100)),
                ('proof_upload', models.FileField(blank=True, help_text='Bank debit alert screenshot or PDF', null=True, upload_to='withdrawal_proofs/%Y/%m/')),
                ('proof_notes', models.TextField(blank=True, help_text='Any additional notes the user provides about the proof')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Bank transfer reference from payout processor', max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterField(
            model_name='affiliateprofile',
            name='application_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productboost',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productboost',
            name='final_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productboost',
            name='original_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productboost',
            name='tier_at_purchase',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_id'], name='Dashboard_t_referen_09745b_idx'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='Dashboard.useraccount'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='monnify_transaction',
            field=models.ForeignKey(blank=True, help_text='Select the Monnify deposit transaction as proof', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='Dashboard.monnifytransaction'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, help_text='The Transaction record created when withdrawal is completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='Dashboard.transaction'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['account', 'status'], name='Dashboard_w_account_ac77d3_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', '-submitted_at'], name='Dashboard_w_status_628464_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['reference'], name='Dashboard_w_referen_adc91b_idx'),
        ),
    ]
