# Generated by Django 5.1.7 on 2025-05-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_listing',
            name='listing_type',
            field=models.CharField(choices=[('standard', 'Standard Listing (45 days)'), ('business', 'Business Listing (90 days)'), ('urgent', 'Urgent Sale (30 days)'), ('permanent', 'Permanent Retail Listing')], default='standard', max_length=10),
        ),
    ]
