# Generated by Django 5.0.1 on 2024-07-11 11:37

import Home.utils
import django.db.models.deletion
from django.db import migrations, models

def populate_initial_data(apps, schema_editor):
    from Home.models import create_initial_data
    create_initial_data()

class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('User', '0004_alter_profile_location_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(null=True, upload_to=Home.utils.user_listing_path),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.location'),
        ),
        migrations.RunPython(populate_initial_data),
    ]
