# Generated by Django 5.0.1 on 2024-07-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_listing_image_listing_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='subcategory',
        ),
    ]
