# Generated by Django 5.0.1 on 2024-07-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_listing_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.subcategory'),
        ),
    ]
