# Generated by Django 5.1.7 on 2025-06-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_aidescriptionusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_listing',
            name='boost_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Combined score for sorting (boost + pro status)', max_digits=10),
        ),
    ]
