# Generated by Django 5.1.7 on 2025-06-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_banner_background_color_banner_is_compact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, default='Advertisement Banner', max_length=100, null=True),
        ),
    ]
