# Generated by Django 5.1.7 on 2025-06-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional: Additional text below the title', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, help_text='Optional: Leave empty if text is included in the image', max_length=100, null=True),
        ),
    ]
