# Generated by Django 5.0.1 on 2024-07-16 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_category_parent_brand_slug_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_listing',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Home.brand'),
        ),
    ]
