# Generated by Django 5.1.7 on 2025-06-28 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_banner_subtitle_alter_banner_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.AlterField(
            model_name='banner',
            name='background_color',
            field=models.CharField(blank=True, help_text='Optional: Hex color code for banner background (e.g., #FF5733)', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Optional: When to stop showing this banner', null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Advertisement image with all text and design elements included', upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Mobile-optimized version of the advertisement', null=True, upload_to='banners/mobile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher number means higher priority in display order'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Optional: When to start showing this banner', null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(help_text='Destination URL when banner is clicked'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['priority', 'updated_at'], name='Home_banner_priorit_381b59_idx'),
        ),
    ]
