# Generated by Django 5.0.1 on 2024-07-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(related_name='brands', to='Home.category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='subcategories',
            field=models.ManyToManyField(related_name='brands', to='Home.subcategory'),
        ),
        migrations.AlterField(
            model_name='product_listing',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.category'),
        ),
    ]
