# Generated by Django 5.0.1 on 2024-07-22 19:42

import Home.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_brand_categories_brand_subcategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_listing',
            name='image',
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=Home.utils.user_listing_path)),
                ('product_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Home.product_listing')),
            ],
        ),
    ]
