# Generated by Django 5.1.7 on 2025-07-05 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_remove_banner_banner_type_remove_banner_is_compact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Advertisement image: 1200x200px (desktop). All banner positions use same dimensions.', upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Mobile-optimized version: 800x200px. Same dimensions for all positions.', null=True, upload_to='banners/mobile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='product_listing',
            name='listing_type',
            field=models.CharField(choices=[('standard', 'Standard Listing (45 days)'), ('urgent', 'Urgent Sale (30 days)'), ('permanent', 'Permanent Retail Listing')], default='standard', max_length=10),
        ),
    ]
