# Generated by Django 5.2.4 on 2025-12-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_banner_image_alter_banner_mobile_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='savedproduct',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductReport',
        ),
        migrations.DeleteModel(
            name='SavedProduct',
        ),
    ]
