# Generated by Django 5.0.1 on 2024-07-22 20:59

import Home.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_product_listing_image_delete_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_listing',
            name='image',
        ),
        migrations.AddField(
            model_name='product_listing',
            name='images',
            field=models.FileField(null=True, upload_to=Home.utils.user_listing_path),
        ),
    ]
