# Generated by Django 5.2.4 on 2026-05-21 22:07

import Home.models
import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_savedproduct_unique_together_and_more'),
        ('User', '0009_alter_businessverificationdocument_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=Home.models.user_receipt_path)),
                ('receipt_type', models.CharField(choices=[('store_receipt', 'Store Receipt'), ('bank_transfer', 'Bank Transfer / Payment Proof'), ('warranty_card', 'Warranty Card'), ('invoice', 'Invoice'), ('packaging', 'Original Box / Packaging Photo'), ('other', 'Other Proof')], default='store_receipt', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product_listing',
            name='bundle_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='delivery_available',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='has_receipt',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='inspection_allowed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='inspection_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='negotiable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='original_accessories_included',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='reason_for_selling',
            field=models.CharField(blank=True, choices=[('upgrading', 'Upgrading to a newer model'), ('no_longer_needed', 'No longer needed'), ('relocating', 'Relocating'), ('decluttering', 'Decluttering'), ('duplicate_gift', 'Received as duplicate/gift'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='receipt_visibility',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('on_request', 'On Request')], default='public', max_length=15),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='swap_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='swap_preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='product_listing',
            index=models.Index(fields=['condition', 'created_at'], name='Home_produc_conditi_65ae49_idx'),
        ),
        migrations.AddIndex(
            model_name='product_listing',
            index=models.Index(fields=['has_receipt'], name='Home_produc_has_rec_f0f044_idx'),
        ),
        migrations.AddIndex(
            model_name='product_listing',
            index=models.Index(fields=['negotiable'], name='Home_produc_negotia_9c40ad_idx'),
        ),
        migrations.AddIndex(
            model_name='product_listing',
            index=models.Index(fields=['delivery_available'], name='Home_produc_deliver_594175_idx'),
        ),
        migrations.AddIndex(
            model_name='product_listing',
            index=models.Index(fields=['swap_accepted'], name='Home_produc_swap_ac_b36714_idx'),
        ),
        migrations.AddIndex(
            model_name='product_listing',
            index=models.Index(fields=['seller', 'created_at'], name='Home_produc_seller__133c47_idx'),
        ),
        migrations.AddField(
            model_name='product_receipt',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='Home.product_listing'),
        ),
    ]
