# Generated by Django 5.0.1 on 2024-07-22 21:09

import Home.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_remove_product_listing_image_product_listing_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_listing',
            name='images',
        ),
        migrations.AddField(
            model_name='product_listing',
            name='image',
            field=models.ImageField(null=True, upload_to=Home.utils.user_listing_path),
        ),
    ]
