# Generated by Django 5.0.1 on 2024-07-23 11:21

import Home.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_remove_product_listing_images_product_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_listing',
            name='image',
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to=Home.utils.user_listing_path)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Home.product_listing')),
            ],
        ),
    ]
