# Generated by Django 5.0.1 on 2024-07-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_remove_product_listing_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
