# Generated by Django 5.0.1 on 2024-07-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_product_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_listing',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
