# Generated by Django 5.0.1 on 2024-07-31 09:26

import Home.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_product_listing_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Home.utils.user_listing_path),
        ),
    ]
