# Generated by Django 5.0.1 on 2024-08-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_listing',
            name='deletion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
