# Generated by Django 5.0.1 on 2024-08-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_product_listing_deletion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_listing',
            name='deletion_date',
        ),
        migrations.RemoveField(
            model_name='product_listing',
            name='last_updated',
        ),
    ]
