# Generated by Django 5.0.1 on 2024-09-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_review_updated_at_reviewreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='ReviewReply',
        ),
    ]
