# Generated by Django 5.0.1 on 2024-11-16 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_review_is_reply_review_level_review_lft_and_more'),
        ('User', '0007_remove_message_conversation_remove_message_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reply', False)), fields=('reviewer', 'product'), name='unique_product_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reply', False)), fields=('reviewer', 'seller'), name='unique_seller_review'),
        ),
    ]
