# Generated by Django 5.0.1 on 2024-12-25 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_alter_review_unique_together_and_more'),
        ('User', '0007_remove_message_conversation_remove_message_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Review replies',
            },
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_product_review',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_seller_review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_reply',
        ),
        migrations.RemoveField(
            model_name='review',
            name='level',
        ),
        migrations.RemoveField(
            model_name='review',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='review',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tree_id',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewer', 'product'), name='unique_product_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewer', 'seller'), name='unique_seller_review'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Home.review'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
