# Generated by Django 5.0.1 on 2025-01-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_savedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_listing',
            name='deletion_warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='is_always_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='last_stock_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='listing_type',
            field=models.CharField(choices=[('standard', 'Standard Listing (7 days)'), ('premium', 'Premium Listing (30 days)'), ('emergency', 'Emergency Sale (3 days)'), ('permanent', 'Permanent Retail Listing')], default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product_listing',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
