# Generated by Django 5.0.1 on 2025-02-09 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_product_listing_deletion_warning_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.category'),
        ),
    ]
