# Generated by Django 5.0.1 on 2025-02-13 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0030_alter_product_listing_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-priority', '-updated_at']},
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('hero', 'Hero Banner'), ('promotional', 'Promotional Banner'), ('announcement', 'Announcement Banner')], default='promotional', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='display_location',
            field=models.CharField(choices=[('home_top', 'Home Page Top'), ('home_middle', 'Home Page Middle'), ('category', 'Category Pages'), ('global', 'Global')], default='home_top', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optimized image for mobile devices', null=True, upload_to='banners/mobile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher number means higher priority'),
        ),
        migrations.AddField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='Advertisement Banner', max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['is_active', 'display_location'], name='Home_banner_is_acti_408e00_idx'),
        ),
    ]
