# Generated by Django 5.0.1 on 2025-02-18 13:53

import Home.utils
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0031_alter_banner_options_banner_banner_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=Home.utils.user_listing_path),
        ),
        migrations.AlterField(
            model_name='product_listing',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=4),
        ),
    ]
