# Generated by Django 5.2.4 on 2025-07-27 02:12

import BuyerRequest.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0011_alter_banner_image_alter_banner_mobile_image_and_more'),
        ('User', '0006_profile_business_last_verification_attempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='What are you looking for?', max_length=255)),
                ('description', models.TextField(help_text='Provide detailed information about what you need')),
                ('request_type', models.CharField(choices=[('product', 'Product/Item'), ('service', 'Service'), ('skill', 'Skill/Expertise')], default='product', max_length=10)),
                ('budget_range', models.CharField(choices=[('under_10k', 'Under ₦10,000'), ('10k_50k', '₦10,000 - ₦50,000'), ('50k_200k', '₦50,000 - ₦200,000'), ('200k_500k', '₦200,000 - ₦500,000'), ('500k_plus', 'Above ₦500,000'), ('custom', 'Custom Range'), ('negotiable', 'Negotiable')], default='negotiable', max_length=20)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget (for custom range)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget (for custom range)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preferred_condition', models.CharField(choices=[('new', 'New Only'), ('used', 'Used Only'), ('any', 'Any Condition')], default='any', max_length=10)),
                ('urgency', models.CharField(choices=[('low', 'Low - I can wait'), ('medium', 'Medium - Within a week'), ('high', 'High - Within 3 days'), ('urgent', 'Urgent - ASAP')], default='medium', max_length=10)),
                ('needed_by', models.DateTimeField(blank=True, help_text='When do you need this?', null=True)),
                ('quantity_needed', models.PositiveIntegerField(default=1, help_text='Quantity needed')),
                ('accept_nationwide', models.BooleanField(default=True, help_text='Accept responses from anywhere in Nigeria')),
                ('show_phone', models.BooleanField(default=False, help_text='Show your phone number to responders')),
                ('contact_instructions', models.TextField(blank=True, help_text='Additional contact instructions')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured request (Pro users)')),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('last_bumped', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('contact_count', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_requests', to='Home.brand')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_requests', to='User.profile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_requests', to='Home.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.location')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_requests', to='Home.subcategory')),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Request',
                'verbose_name_plural': 'Buyer Requests',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=BuyerRequest.models.buyer_request_image_path)),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='BuyerRequest.buyerrequest')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyerRequest.buyerrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='BuyerRequest.buyerrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(help_text='Describe what you can offer')),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, help_text='Your offered price (optional)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('availability', models.CharField(blank=True, help_text='When can you deliver/provide this?', max_length=255)),
                ('condition_offered', models.CharField(blank=True, choices=[('new', 'New Only'), ('used', 'Used Only'), ('any', 'Any Condition')], max_length=10)),
                ('quantity_available', models.PositiveIntegerField(blank=True, help_text='Quantity available', null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed by Buyer'), ('interested', 'Buyer Interested'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified_seller', models.BooleanField(default=False)),
                ('is_featured_response', models.BooleanField(default=False)),
                ('buyer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='BuyerRequest.buyerrequest')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_responses', to='User.profile')),
            ],
            options={
                'ordering': ['-is_featured_response', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='buyerrequest',
            index=models.Index(fields=['status', '-created_at'], name='BuyerReques_status_16d023_idx'),
        ),
        migrations.AddIndex(
            model_name='buyerrequest',
            index=models.Index(fields=['category', 'status'], name='BuyerReques_categor_5920c9_idx'),
        ),
        migrations.AddIndex(
            model_name='buyerrequest',
            index=models.Index(fields=['buyer', '-created_at'], name='BuyerReques_buyer_i_918455_idx'),
        ),
        migrations.AddIndex(
            model_name='buyerrequest',
            index=models.Index(fields=['expires_at', 'status'], name='BuyerReques_expires_ae038d_idx'),
        ),
        migrations.AddIndex(
            model_name='buyerrequest',
            index=models.Index(fields=['is_featured', '-created_at'], name='BuyerReques_is_feat_f7bfc6_idx'),
        ),
        migrations.AddIndex(
            model_name='requestaccess',
            index=models.Index(fields=['user', 'accessed_at'], name='BuyerReques_user_id_01a155_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requestaccess',
            unique_together={('user', 'request')},
        ),
        migrations.AlterUniqueTogether(
            name='savedrequest',
            unique_together={('user', 'request')},
        ),
        migrations.AddIndex(
            model_name='sellerresponse',
            index=models.Index(fields=['buyer_request', '-created_at'], name='BuyerReques_buyer_r_515704_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerresponse',
            index=models.Index(fields=['seller', '-created_at'], name='BuyerReques_seller__05845f_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerresponse',
            index=models.Index(fields=['status', '-created_at'], name='BuyerReques_status_25695e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerresponse',
            unique_together={('buyer_request', 'seller')},
        ),
    ]
