# Generated by Django 5.2.4 on 2025-12-30 18:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyerRequest', '0001_initial'),
        ('Home', '0012_alter_savedproduct_unique_together_and_more'),
        ('Services', '0002_remove_serviceconversation_participants_and_more'),
        ('User', '0007_bulkemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedrequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='savedrequest',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='buyerrequest',
            options={'ordering': ['-is_featured', '-boost_score', '-created_at'], 'verbose_name': 'Buyer Request', 'verbose_name_plural': 'Buyer Requests'},
        ),
        migrations.AlterModelOptions(
            name='requestaccess',
            options={'ordering': ['-accessed_at']},
        ),
        migrations.AlterModelOptions(
            name='sellerresponse',
            options={'ordering': ['-is_featured_response', '-response_score', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='buyerrequest',
            name='BuyerReques_is_feat_f7bfc6_idx',
        ),
        migrations.RemoveIndex(
            model_name='requestaccess',
            name='BuyerReques_user_id_01a155_idx',
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='boost_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Combined score for sorting (boost + pro status)', max_digits=10),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='deletion_warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='delivery_preference',
            field=models.CharField(choices=[('remote', 'Remote/Online'), ('onsite', 'On-site'), ('both', 'Either'), ('no_preference', 'No Preference')], default='no_preference', help_text='Delivery preference (for services)', max_length=20),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='project_duration',
            field=models.CharField(blank=True, help_text='Expected project duration (for services)', max_length=100),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='service_category',
            field=models.CharField(blank=True, choices=[('technology', 'Technology & Digital'), ('creative', 'Creative & Design'), ('business', 'Business Services'), ('home', 'Home & Lifestyle'), ('health', 'Health & Beauty'), ('professional', 'Professional Services')], help_text='Select if looking for a service', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='skill_level_required',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced'), ('expert', 'Expert'), ('any', 'Any Level')], default='any', help_text='Required skill level (for services)', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerresponse',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any additional information'),
        ),
        migrations.AddField(
            model_name='sellerresponse',
            name='delivery_time',
            field=models.CharField(blank=True, help_text='Delivery/completion time', max_length=100),
        ),
        migrations.AddField(
            model_name='sellerresponse',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('platform', 'Through Platform')], default='platform', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerresponse',
            name='related_product',
            field=models.ForeignKey(blank=True, help_text='Link to your existing product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_request_responses', to='Home.product_listing'),
        ),
        migrations.AddField(
            model_name='sellerresponse',
            name='related_service',
            field=models.ForeignKey(blank=True, help_text='Link to your existing service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_request_responses', to='Services.servicelisting'),
        ),
        migrations.AddField(
            model_name='sellerresponse',
            name='response_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Response quality score', max_digits=10),
        ),
        migrations.AddField(
            model_name='sellerresponse',
            name='response_type',
            field=models.CharField(choices=[('existing_product', 'I have a product that matches'), ('existing_service', 'I offer a service that matches'), ('custom_product', 'I can source/create this product'), ('custom_service', 'I can provide this service'), ('hybrid', 'I can provide both product & service')], default='custom_product', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerresponse',
            name='service_includes',
            field=models.TextField(blank=True, help_text="What's included in the service"),
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Preferred brand (for products)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_requests', to='Home.brand'),
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='budget_range',
            field=models.CharField(choices=[('under_5k', 'Under ₦5,000'), ('5k_25k', '₦5,000 - ₦25,000'), ('25k_100k', '₦25,000 - ₦100,000'), ('100k_500k', '₦100,000 - ₦500,000'), ('500k_1m', '₦500,000 - ₦1,000,000'), ('1m_plus', 'Above ₦1,000,000'), ('custom', 'Custom Range'), ('negotiable', 'Negotiable')], default='negotiable', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category (for product requests)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_requests', to='Home.category'),
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured request'),
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='preferred_condition',
            field=models.CharField(choices=[('new', 'New Only'), ('used', 'Used Only'), ('any', 'Any Condition'), ('not_applicable', 'Not Applicable')], default='any', max_length=15),
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='quantity_needed',
            field=models.PositiveIntegerField(default=1, help_text='Quantity needed (for products)'),
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='request_type',
            field=models.CharField(choices=[('product', 'Looking for a Product'), ('service', 'Looking for a Service'), ('both', 'Open to Both Products & Services')], default='product', max_length=10),
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Product subcategory (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_requests', to='Home.subcategory'),
        ),
        migrations.AlterField(
            model_name='requestaccess',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='BuyerRequest.buyerrequest'),
        ),
        migrations.AlterField(
            model_name='requestaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellerresponse',
            name='condition_offered',
            field=models.CharField(blank=True, choices=[('new', 'New Only'), ('used', 'Used Only'), ('any', 'Any Condition'), ('not_applicable', 'Not Applicable')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sellerresponse',
            name='message',
            field=models.TextField(help_text='Describe how you can help with this request'),
        ),
        migrations.AlterField(
            model_name='sellerresponse',
            name='offered_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Your offered price', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='sellerresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed by Buyer'), ('interested', 'Buyer Interested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='buyerrequest',
            index=models.Index(fields=['service_category', 'status'], name='BuyerReques_service_ca73e5_idx'),
        ),
        migrations.AddIndex(
            model_name='buyerrequest',
            index=models.Index(fields=['is_featured', '-boost_score'], name='BuyerReques_is_feat_7ec5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='buyerrequest',
            index=models.Index(fields=['request_type', 'status'], name='BuyerReques_request_234449_idx'),
        ),
        migrations.AddIndex(
            model_name='requestaccess',
            index=models.Index(fields=['user', '-accessed_at'], name='BuyerReques_user_id_c7c41a_idx'),
        ),
        migrations.AddIndex(
            model_name='requestaccess',
            index=models.Index(fields=['request', '-accessed_at'], name='BuyerReques_request_92cb58_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerresponse',
            index=models.Index(fields=['-is_featured_response', '-response_score'], name='BuyerReques_is_feat_0bdc1e_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerresponse',
            index=models.Index(fields=['response_type'], name='BuyerReques_respons_37afa9_idx'),
        ),
        migrations.DeleteModel(
            name='SavedRequest',
        ),
    ]
