# Generated by Django 5.2.4 on 2026-03-18 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyerRequest', '0002_alter_savedrequest_unique_together_and_more'),
        ('Messages', '0004_add_conversation_to_inquiry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sellerresponse',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_response', to='Messages.conversation'),
        ),
    ]
