# Generated by Django 5.2.4 on 2026-06-23 22:02

import BuyerRequest.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyerRequest', '0003_add_conversation_to_seller_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerrequestimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=BuyerRequest.models.buyer_request_image_path),
        ),
    ]
