# Generated by Django 5.1.7 on 2025-05-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_content',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='inquiry_type',
            field=models.CharField(choices=[('AVAILABILITY', 'Is this product available?'), ('MORE_INFO', 'I would like more information about this product'), ('PRICE_NEGOTIATION', 'Is the price negotiable?'), ('LOCATION', 'Where can I inspect or pick up the product?'), ('DELIVERY', 'Do you offer delivery services?'), ('PAYMENT_METHOD', 'What payment methods do you accept?'), ('WARRANTY', 'Does this product come with a warranty or guarantee?'), ('CONDITION', 'What is the condition of the product?'), ('CUSTOM', 'Custom message')], max_length=20),
        ),
    ]
