# Generated by Django 5.2.4 on 2025-12-30 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_message_encrypted_content_alter_message_content_and_more'),
        ('User', '0007_bulkemail'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='product',
        ),
        migrations.AddField(
            model_name='conversation',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='object_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='inquiry_type',
            field=models.CharField(choices=[('AVAILABILITY', 'Is this available?'), ('MORE_INFO', 'I would like more information'), ('PRICE_NEGOTIATION', 'Is the price negotiable?'), ('LOCATION', 'Where can I inspect or pick up?'), ('DELIVERY', 'Do you offer delivery services?'), ('PAYMENT_METHOD', 'What payment methods do you accept?'), ('WARRANTY', 'Does this come with a warranty?'), ('CONDITION', 'What is the condition?'), ('SERVICE_INQUIRY', 'Service inquiry'), ('REQUEST_RESPONSE', 'Response to request'), ('CUSTOM', 'Custom message')], default='CUSTOM', max_length=20),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['content_type', 'object_id'], name='Messages_co_content_feccc7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='Messages_co_updated_060e94_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='Messages_me_convers_27ed13_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='Messages_me_is_read_339005_idx'),
        ),
    ]
