# Generated by Django 5.2.4 on 2026-03-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0003_alter_message_options_remove_conversation_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='inquiry_type',
            field=models.CharField(choices=[('AVAILABILITY', 'Is this available?'), ('MORE_INFO', 'I would like more information'), ('PRICE_NEGOTIATION', 'Is the price negotiable?'), ('LOCATION', 'Where can I inspect or pick up?'), ('DELIVERY', 'Do you offer delivery services?'), ('PAYMENT_METHOD', 'What payment methods do you accept?'), ('WARRANTY', 'Does this come with a warranty?'), ('CONDITION', 'What is the condition?'), ('SERVICE_INQUIRY', 'Service inquiry'), ('REQUEST_RESPONSE', 'Response to request'), ('CUSTOM', 'Custom message'), ('SERVICE_INQUIRY_CARD', 'Service Inquiry Card'), ('SELLER_RESPONSE_CARD', 'Seller Response Card')], default='CUSTOM', max_length=20),
        ),
    ]
