# Generated by Django 5.1.7 on 2025-05-17 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_profile_email_otp_profile_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_marketing', models.BooleanField(default=True, help_text='Marketing emails and newsletters')),
                ('receive_announcements', models.BooleanField(default=True, help_text='Important announcements about OpenSell')),
                ('receive_notifications', models.BooleanField(default=True, help_text='Activity notifications')),
                ('unsubscribe_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to='User.profile')),
            ],
        ),
    ]
