# Generated by Django 5.1.7 on 2025-05-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_emailpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_products_listed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
