# Generated by Django 5.0.1 on 2024-08-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
