# Generated by Django 5.2.4 on 2025-12-30 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_bulkemail'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_for_services',
            field=models.BooleanField(default=False, help_text='Available to provide services'),
        ),
        migrations.AddField(
            model_name='profile',
            name='buyer_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating as buyer', max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_title',
            field=models.CharField(blank=True, help_text="Professional title (e.g., 'Graphic Designer', 'Web Developer')", max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_availability_note',
            field=models.CharField(blank=True, help_text='Brief note about your availability', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_provider_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating as service provider', max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='List of skills separated by commas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_buyer_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total reviews as buyer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_requests_posted',
            field=models.PositiveIntegerField(default=0, help_text='Total buyer requests posted'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_service_inquiries',
            field=models.PositiveIntegerField(default=0, help_text='Total service inquiries received'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_service_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total reviews as service provider'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_services_listed',
            field=models.PositiveIntegerField(default=0, help_text='Total services ever listed'),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of professional experience', null=True),
        ),
        migrations.CreateModel(
            name='ItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('spam', 'Spam or Misleading Content'), ('fraud', 'Fraudulent Listing'), ('inappropriate', 'Inappropriate Content'), ('expired', 'Expired or Sold Item'), ('scam', 'Suspected Scam'), ('fake', 'Fake Listing'), ('duplicate', 'Duplicate Listing'), ('other', 'Other Reason')], max_length=20)),
                ('details', models.TextField()),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_item_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Report',
                'verbose_name_plural': 'Item Reports',
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='User_itemre_content_a4f436_idx'), models.Index(fields=['status', '-reported_at'], name='User_itemre_status_9408f1_idx'), models.Index(fields=['reviewed_by', '-reviewed_at'], name='User_itemre_reviewe_446239_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', '-saved_at'], name='User_savedi_user_id_341fdd_idx'), models.Index(fields=['content_type', 'object_id'], name='User_savedi_content_54c572_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
