# Generated by Django 5.2.4 on 2025-11-27 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_profile_business_last_verification_attempt_and_more.py'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(choices=[('marketing', 'Marketing'), ('announcement', 'Announcement'), ('notification', 'Notification')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Plain HTML content')),
                ('target_all', models.BooleanField(default=True)),
                ('verified_only', models.BooleanField(default=False)),
                ('business_only', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('total_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='User_bulkem_status_4a7643_idx')],
            },
        ),
    ]
