# Generated by Django 5.0.1 on 2025-02-18 14:06

import User.utils
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_message_conversation_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=User.utils.user_directory_path),
        ),
    ]
