# Generated by Django 5.2.4 on 2026-05-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_profile_available_for_services_profile_buyer_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessverificationdocument',
            name='document_type',
            field=models.CharField(choices=[('business_registration', 'Business Registration Certificate'), ('tax_certificate', 'Tax Identification Certificate'), ('business_license', 'Business License'), ('bank_statement', 'Bank Statement'), ('utility_bill', 'Utility Bill'), ('other', 'Other Document')], default='business_registration', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('limited_liability', 'Limited Liability Company'), ('corporation', 'Corporation'), ('cooperative', 'Cooperative Society'), ('ngo', 'Non-Governmental Organization'), ('other', 'Other')], default='sole_proprietorship', max_length=50, null=True),
        ),
    ]
