# Generated by Django 5.2.4 on 2026-05-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_businessverificationdocument_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='available_for_services',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='service_availability_note',
        ),
    ]
