# Generated by Django 5.0.1 on 2025-02-19 12:19

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_location_lga_alter_location_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NigerianLGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': 'LGAs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NigerianState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_southwest', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['state', 'lga']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='district',
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='NG', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='location',
            name='lga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='User.nigerianlga', verbose_name='Local Government Area'),
        ),
        migrations.AddField(
            model_name='nigerianlga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='User.nigerianstate'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='User.nigerianstate'),
        ),
    ]
