# Generated by Django 5.0.1 on 2025-02-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_nigerianlga_nigerianstate_alter_location_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='lga',
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.DeleteModel(
            name='NigerianLGA',
        ),
        migrations.DeleteModel(
            name='NigerianState',
        ),
    ]
