# Generated by Django 5.1.7 on 2025-07-23 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_digest',
            field=models.BooleanField(default=False, help_text='Receive weekly email digest'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_notifications',
            field=models.BooleanField(default=False, help_text='Receive notifications via email'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='frequency',
            field=models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly digest'), ('daily', 'Daily digest')], default='instant', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='milestone_achievements',
            field=models.BooleanField(default=True, help_text='Get notified about milestones and achievements'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='price_drop_alerts',
            field=models.BooleanField(default=True, help_text='Get notified about price drops on saved items'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Receive browser push notifications'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='reply_notifications',
            field=models.BooleanField(default=True, help_text='Get notified about replies to your reviews'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='report_notifications',
            field=models.BooleanField(default=True, help_text='Get notified if your listings are reported'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('announcement', '📢 Announcements'), ('system', '⚙️ System'), ('news', '📰 News & Updates'), ('review', '⭐ Reviews'), ('saves', '❤️ Saves & Favorites'), ('milestones', '🎯 Milestones'), ('alerts', '🚨 Alerts')], default='announcement', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='deletion_warnings',
            field=models.BooleanField(default=True, help_text='Get notified when listings are about to expire'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='review_notifications',
            field=models.BooleanField(default=True, help_text='Get notified about new reviews'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='save_notifications',
            field=models.BooleanField(default=True, help_text='Get notified when someone saves your listings'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='stock_alerts',
            field=models.BooleanField(default=True, help_text='Get notified about low stock'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='system_notifications',
            field=models.BooleanField(default=True, help_text='Get notified about system updates'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='view_milestone_notifications',
            field=models.BooleanField(default=True, help_text='Get notified about view milestones'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='Notificatio_is_read_4281eb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='Notificatio_priorit_8e9cc4_idx'),
        ),
    ]
