# Generated by Django 5.2.4 on 2026-05-24 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_notification_action_text_notification_action_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='transaction_notifications',
            field=models.BooleanField(default=True, help_text='Get notified about wallet deposits, withdrawals, transfers, subscriptions, and payments'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.TextField(blank=True, help_text='Relative or absolute URL for the action button', null=True),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField(help_text='Public key for payload encryption')),
                ('auth', models.TextField(help_text='Auth secret')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'active'], name='Notificatio_user_id_6e3fde_idx')],
            },
        ),
    ]
